### ISSUE TITLE
update docker image

### ISSUE THREAD

**Issue by mictadlo** [wurmlab/oswitch#30]
Hello, great project. 
How is it possible to update regularly a docker image such as bio-linux?

Thank you in advance.

Cheers,

Michal

**Comment by yeban** [comment]
Thanks :).

To pull a new, updated image you could specify a tag together with the repo/image name, like you would do with docker.

```
oswitch yeban/biolinux:8 # Similar to, docker run -it yeban/biolinux:8
```

But I'm not sure if that's what you are looking for. If you want to update the BioLinux image you pulled in from some repo (say, yeban/biolinux) you could do something like:

```
oswitch yeban/biolinux:8

# in container
# update biolinux
sudo apt-get update
sudo apt-get upgrade # or dist-upgrade

# outside container
docker ps # from here note id of the biolinux container (e.g., biolinux-1234)
docker commit -m "Updated packages." <biolinux-1234> mictadlo/yeban_biolinux_8:20150906
docker push ...

# use the new, updated image
oswitch mictadlo/yeban_biolinux_8:20150906
```

**Comment by mictadlo** [comment]
Thank you.
