### ISSUE TITLE
How to install oswich for all users

### ISSUE THREAD

**Issue by mictadlo** [wurmlab/oswitch#31]
Hello, How is it possible to install oswitch systemwide so everybody has access to it?

Thank you in advance.

Mic

**Comment by yannickwurm** [comment]
Hey Michał - priyam is away right now but he'll probably get back to you late this week or early next when he's back

cheers
Y

**Comment by yeban** [comment]
Hey Mic,

This depends largely on the OS. Are you running oswitch on Linux or Mac? If it's Debian or Ubuntu you can install oswitch systemwide via apt. oswitch deb packages are available from NERC's BioLinux ppa on launchpad.

```
sudo add-apt-repository ppa:nebc/biolinux
sudo apt-get update
sudo apt-get install oswitch
```

If it's Mac, you can install systemwide using homebrew.

```
brew install https://raw.githubusercontent.com/yeban/oswitch/master/homebrew/oswitch.rb
```

**Comment by mictadlo** [comment]
Thank you Y and yeban. It is actually CentOS 6.6.

**Comment by yeban** [comment]
We don't have rpm package for oswitch yet. But installing oswitch via RubyGems (which in turn was installed from CentOS' package manager) should work.
