### ISSUE TITLE
Error: image genomics/1:latest not found

### ISSUE THREAD

**Issue by mictadlo** [wurmlab/oswitch#32]
Hello, I am not able anymore to use biolinux, because I got (Error: image genomics/1:latest not found):

	$ oswitch yeban/biolinux:8
	Sending build context to Docker daemon 5.632 kB
	Sending build context to Docker daemon 
	Step 0 : FROM yeban/biolinux:8
	Pulling repository yeban/biolinux
	966da3e7798b: Download complete 
	511136ea3c5a: Download complete 
	27d47432a69b: Download complete 
	5f92234dcf1e: Download complete 
	51a9c7c1f8bb: Download complete 
	5ba9dab47459: Download complete 
	188eb3d62263: Download complete 
	2175b37d5d02: Download complete 
	0aa794bccd7e: Download complete 
	fc3c32a1c978: Download complete 
	Status: Image is up to date for yeban/biolinux:8
	 ---> 966da3e7798b
	Step 1 : COPY _switch /
	 ---> f029f5d4ec76
	Removing intermediate container 63a8590579a4
	Step 2 : COPY wheel /etc/sudoers.d/
	 ---> 9e1e2b7ad952
	Removing intermediate container aeee952eb913
	Step 3 : RUN /_switch 503 503 lorencm /home/lorencm bash 2>&1 | tee /tmp/oswitch.log
	 ---> Running in 65330de02638

	Switch-ifying ...

	Assuming Ubuntu.
	Attempting to activate universe and multiverse repositories.
	Reading package lists...
	Building dependency tree...
	Reading state information...
	software-properties-common is already the newest version.
	0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
	'universe' distribution component is already enabled for all sources.
	'multiverse' distribution component is already enabled for all sources.

	Updating list of packages.
	Ign http://dl.google.com stable InRelease
	...
	Get:56 http://ppa.launchpad.net trusty/main i386 Packages [20.6 kB]
	Fetched 5832 kB in 21s (270 kB/s)
	Reading package lists...
	W: Size of file /var/lib/apt/lists/dl.google.com_linux_chrome_deb_dists_stable_main_binary-amd64_Packages.gz is not what the server reported 966 974
	W: Size of file /var/lib/apt/lists/dl.google.com_linux_chrome_deb_dists_stable_main_binary-i386_Packages.gz is not what the server reported 960 970
	W: Size of file /var/lib/apt/lists/dl.google.com_linux_talkplugin_deb_dists_stable_main_binary-amd64_Packages.gz is not what the server reported 659 671
	W: Size of file /var/lib/apt/lists/dl.google.com_linux_talkplugin_deb_dists_stable_main_binary-i386_Packages.gz is not what the server reported 661 669
	W: Size of file /var/lib/apt/lists/nebc.nerc.ac.uk_bio-linux_dists_unstable_bio-linux_binary-amd64_Packages.gz is not what the server reported 45901 46156
	W: Size of file /var/lib/apt/lists/nebc.nerc.ac.uk_bio-linux_dists_unstable_bio-linux_binary-i386_Packages.gz is not what the server reported 34821 35062

	Installing utilities.
	Reading package lists...
	Building dependency tree...
	Reading state information...
	less is already the newest version.
	The following packages will be upgraded:
	  sudo
	1 upgraded, 0 newly installed, 0 to remove and 564 not upgraded.
	Need to get 343 kB of archives.
	After this operation, 20.5 kB disk space will be freed.
	Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main sudo amd64 1.8.9p5-1ubuntu1.1 [343 kB]
	Fetched 343 kB in 4s (76.8 kB/s)
	(Reading database ... 236328 files and directories currently installed.)
	Preparing to unpack .../sudo_1.8.9p5-1ubuntu1.1_amd64.deb ...
	invoke-rc.d: policy-rc.d denied execution of stop.
	Unpacking sudo (1.8.9p5-1ubuntu1.1) over (1.8.9p5-1ubuntu1) ...
	Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
	Processing triggers for ureadahead (0.100.0-16) ...
	Setting up sudo (1.8.9p5-1ubuntu1.1) ...

	Setting up locale.
	Reading package lists...
	Building dependency tree...
	Reading state information...
	locales is already the newest version.
	0 upgraded, 0 newly installed, 0 to remove and 564 not upgraded.
	Generating locales...
	  en_US.UTF-8... done
	Generation complete.

	Installing bash as requested.
	Reading package lists...
	Building dependency tree...
	Reading state information...
	bash is already the newest version.
	0 upgraded, 0 newly installed, 0 to remove and 564 not upgraded.

	Creating user lorencm with uid 503 ...
	Done.
	Your home directory is .
	You can use sudo.
	passwd: password expiry information changed.
	 ---> ca0c85794cd6
	Removing intermediate container 65330de02638
	Step 4 : ENV LC_ALL en_US.UTF-8
	 ---> Running in af222576c232
	 ---> 80d01b4a4c7f
	Removing intermediate container af222576c232
	Step 5 : USER lorencm
	 ---> Running in b33cfefcf069
	 ---> 31147cb4a38a
	Removing intermediate container b33cfefcf069
	Step 6 : ENTRYPOINT bash -c
	 ---> Running in 300fc7439a27
	 ---> 47aba74b805f
	Removing intermediate container 300fc7439a27
	Successfully built 47aba74b805f
	Unable to find image 'genomics/1:latest' locally
	Pulling repository genomics/1
	Error: image genomics/1:latest not found

What did I do wrong?

Mic

**Comment by mictadlo** [comment]
It is working with
 
     docker run -it yeban/biolinux:8

**Comment by yeban** [comment]
This is strange. Did you try editing (or accidentally modified) the dockerfile created by oswitch in `~/.oswitch`?

**Comment by yeban** [comment]
Does it work if you delete oswitch's yeban/biolinux:8 image (should be named oswitch_yeban_biolinux, but double check by running `docker images`) and then try again with oswitch? Since yeban/biolinux:8 is already on your system (and works with `docker run`), it won't be pulled again.

**Comment by yeban** [comment]
I'm unable to reproduce it.
