### ISSUE TITLE
boot2docker-cli has been depreciated (3 months ago)

### ISSUE THREAD

**Issue by IsmailM** [wurmlab/oswitch#33]
It’s been three months since boot2docker cli was officially depreciated. As such Oswitch should use `docker-machine` instead…

https://github.com/boot2docker/boot2docker-cli

https://docs.docker.com/machine/

**Comment by yeban** [comment]
Right. But not until it docker-machine (via Kitematic) "just works" - the "hung at 99%" issue in particular (https://github.com/kitematic/kitematic/issues/1029).
