### ISSUE TITLE
SHA1 mismatch

### ISSUE THREAD

**Issue by brainstorm** [wurmlab/oswitch#39]
SHA256 is recommended for new Homebrew recipes, but anyway:

```
==> Downloading https://github.com/yeban/oswitch/archive/v0.2.6.tar.gz
==> Downloading from https://codeload.github.com/wurmlab/oswitch/tar.gz/v0.2.6
######################################################################## 100,0%
Error: SHA1 mismatch
Expected: 87d4c9680c40eab6a503d24b7b09e7b069be7c67
Actual: da85f60dee8ce75cff05bf0f795d888d17803dfd
Archive: /Library/Caches/Homebrew/oswitch-0.2.6.tar.gz
To retry an incomplete download, remove the file above.
```

How come you guys don't package it for upstream Homebrew/homebrew-science? This looks like a super useful tool!

**Comment by yeban** [comment]
Ouch. Looks like I forgot to update the SHA when I updated the URL for 0.2.6 release. I will update in a bit.

Thanks for the encouragement :). Maybe you could nominate us for homebrew-science on their repo?

**Comment by brainstorm** [comment]
Any ideas on why this might be happening?:

https://travis-ci.org/Homebrew/homebrew-science/jobs/90970259#L1198
