### ISSUE TITLE
Needs a DOI to be added to bio.tools

### ISSUE THREAD

**Issue by bmpvieira** [wurmlab/oswitch#43]
Tools cannot be registered in [bio.tools](https://bio.tools) unless they have a publication (i.e. a DOI). Otherwise we get a "validation error, required field".

This can be solved by either:
- Publishing a preprint on [arXiv](http://arxiv.org) or [bioRxiv](http://biorxiv.org) (difficulty: writing a paper)
- Submitting a source code release archive to [Figshare](https://mozillascience.github.io/code-research-object/) or [Zenodo](https://guides.github.com/activities/citable-code/) (difficulty: easy)
- Submit to the [Journal of Open Source Software](http://joss.theoj.org/about) (which is something in between). This means, submit an abstract and source code archive; code gets peer reviewed; if accepted you get a DOI. (difficulty: depends on peer review process)

**Comment by bmpvieira** [comment]
Sorry, never mind, I think I can add it to bio.tools without a DOI.

**Comment by yeban** [comment]
Thanks. I will close this issue then.
